@echo off
echo Welcome! This script will go through all your music and sound files in the Custom folder and register them for you automatically!

echo Generating the file for registers...
echo -- libraries > DragonSpeedway-AutoGenerated.lua
echo local LSM = LibStub("LibSharedMedia-3.0") >> DragonSpeedway-AutoGenerated.lua

echo Registering custom Music files...
echo.>> DragonSpeedway-AutoGenerated.lua
echo -- Automatically generated custom music >> DragonSpeedway-AutoGenerated.lua
echo.>> DragonSpeedway-AutoGenerated.lua
for %%F in (Music\Custom\*.*) do (
    if "%%~nxF" NEQ "put-files-here.txt" (
        echo   %%~nF
        echo LSM:Register("sound", "%%~nF", [[Interface\Addons\DragonSpeedway_Music\Music\Custom\%%~nxF]]^) >> DragonSpeedway-AutoGenerated.lua
    )
)

echo Registering custom Sound files...
echo.>> DragonSpeedway-AutoGenerated.lua
echo -- Automatically generated custom sounds >> DragonSpeedway-AutoGenerated.lua
echo.>> DragonSpeedway-AutoGenerated.lua
for %%F in (Sounds\Custom\*.*) do (
    if "%%~nxF" NEQ "put-files-here.txt" (
        echo   %%~nF
        echo LSM:Register("sound", "%%~nF", [[Interface\Addons\DragonSpeedway_Music\Sounds\Custom\%%~nxF]]^) >> DragonSpeedway-AutoGenerated.lua
    )
)

echo Done! Enjoy!
@pause
